sonar.host.url=https://sonarcloud.io
sonar.organization=diegonoss
sonar.projectKey=diegonoss_flipsync
sonar.projectName=flipsync
sonar.sources=src,bin
sonar.tests=tests
sonar.exclusions=dist/**,node_modules/**
sonar.coverage.exclusions=**/*
sonar.issue.ignore.multicriteria=e1,e2,e3
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S2187
sonar.issue.ignore.multicriteria.e1.resourceKey=tests/**
sonar.issue.ignore.multicriteria.e2.ruleKey=tssecurity:S8703
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*
sonar.issue.ignore.multicriteria.e3.ruleKey=tssecurity:S8707
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*
